config/routes.rb
Enegotiation::Application.routes.draw do

  resources :participants

  resources :top_standing_entries

  resources :top_standings

  devise_for :admins
  devise_for :users

  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  root to: 'site#home'

  resources :contact_forms

  match '/about',     to: 'site#about',   via: 'get'
  match '/team',      to: 'site#team',    via: 'get'
  match '/contact',   to: 'site#contact', via: 'get'
  match '/faq',       to: 'site#faq', via: 'get'
  match '/overview',  to: 'site#overview', via: 'get'
  match '/videos',    to: 'site#videos', via: 'get'
  match '/rules',     to: 'site#rules', via: 'get'
  match '/standings', to: 'site#standings', via: 'get'
  match '/participants', to: 'site#participants', via: 'get'
  match '/terms',      to: 'site#terms', via: 'get'
  match '/privacy',      to: 'site#privacy', via: 'get'
  match '/sitemap',      to: 'site#sitemap', via: 'get'
  
  match '/dashboard', to: 'dashboard#index',  via: 'get'

end

app/models/top_standing_entry.rb
class TopStandingEntry < ActiveRecord::Base
  belongs_to :top_standing
end

app/controllers/top_standing_entries_controller.rb
class TopStandingEntriesController < ApplicationController
  before_action :set_top_standing_entry, only: [:show, :edit, :update, :destroy]

  # GET /top_standing_entries
  # GET /top_standing_entries.json
  def index
    @top_standing_entries = TopStandingEntry.all
  end

  # GET /top_standing_entries/1
  # GET /top_standing_entries/1.json
  def show
  end

  # GET /top_standing_entries/new
  def new
    @top_standing_entry = TopStandingEntry.new
  end

  # GET /top_standing_entries/1/edit
  def edit
  end

  # POST /top_standing_entries
  # POST /top_standing_entries.json
  def create
    @top_standing_entry = TopStandingEntry.new(top_standing_entry_params)

    respond_to do |format|
      if @top_standing_entry.save
        format.html { redirect_to @top_standing_entry, notice: 'Top standing entry was successfully created.' }
        format.json { render action: 'show', status: :created, location: @top_standing_entry }
      else
        format.html { render action: 'new' }
        format.json { render json: @top_standing_entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /top_standing_entries/1
  # PATCH/PUT /top_standing_entries/1.json
  def update
    respond_to do |format|
      if @top_standing_entry.update(top_standing_entry_params)
        format.html { redirect_to @top_standing_entry, notice: 'Top standing entry was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @top_standing_entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /top_standing_entries/1
  # DELETE /top_standing_entries/1.json
  def destroy
    @top_standing_entry.destroy
    respond_to do |format|
      format.html { redirect_to top_standing_entries_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_top_standing_entry
      @top_standing_entry = TopStandingEntry.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def top_standing_entry_params
      params.require(:top_standing_entry).permit(:top_standing_id, :rank, :player, :coach, :country, :comments)
    end
end

app/views/top_standing_entries/_form.html.haml
= form_for @top_standing_entry do |f|
  - if @top_standing_entry.errors.any?
    #error_explanation
      %h2= "#{pluralize(@top_standing_entry.errors.count, "error")} prohibited this top_standing_entry from being saved:"
      %ul
        - @top_standing_entry.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :top_standing_id
    = f.number_field :top_standing_id
  .field
    = f.label :rank
    = f.number_field :rank
  .field
    = f.label :player
    = f.text_field :player
  .field
    = f.label :coach
    = f.text_field :coach
  .field
    = f.label :country
    = f.text_field :country
  .field
    = f.label :comments
    = f.text_area :comments
  .actions
    = f.submit 'Save'

app/views/top_standing_entries/edit.html.haml
%h1 Editing top_standing_entry

= render 'form'

= link_to 'Show', @top_standing_entry
\|
= link_to 'Back', top_standing_entries_path

app/views/top_standing_entries/index.html.haml
%h1 Listing top_standing_entries

%table
  %tr
    %th Top standing
    %th Rank
    %th Player
    %th Coach
    %th Country
    %th Comments
    %th
    %th
    %th

  - @top_standing_entries.each do |top_standing_entry|
    %tr
      %td= top_standing_entry.top_standing_id
      %td= top_standing_entry.rank
      %td= top_standing_entry.player
      %td= top_standing_entry.coach
      %td= top_standing_entry.country
      %td= top_standing_entry.comments
      %td= link_to 'Show', top_standing_entry
      %td= link_to 'Edit', edit_top_standing_entry_path(top_standing_entry)
      %td= link_to 'Destroy', top_standing_entry, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Top standing entry', new_top_standing_entry_path

app/views/top_standing_entries/new.html.haml
%h1 New top_standing_entry

= render 'form'

= link_to 'Back', top_standing_entries_path

app/views/top_standing_entries/show.html.haml
%p#notice= notice

%p
  %b Top standing:
  = @top_standing_entry.top_standing_id
%p
  %b Rank:
  = @top_standing_entry.rank
%p
  %b Player:
  = @top_standing_entry.player
%p
  %b Coach:
  = @top_standing_entry.coach
%p
  %b Country:
  = @top_standing_entry.country
%p
  %b Comments:
  = @top_standing_entry.comments

= link_to 'Edit', edit_top_standing_entry_path(@top_standing_entry)
\|
= link_to 'Back', top_standing_entries_path