config/routes.rb
Enegotiation::Application.routes.draw do

  resources :participants

  resources :top_standing_entries

  resources :top_standings

  devise_for :admins
  devise_for :users

  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  root to: 'site#home'

  resources :contact_forms

  match '/about',     to: 'site#about',   via: 'get'
  match '/team',      to: 'site#team',    via: 'get'
  match '/contact',   to: 'site#contact', via: 'get'
  match '/faq',       to: 'site#faq', via: 'get'
  match '/overview',  to: 'site#overview', via: 'get'
  match '/videos',    to: 'site#videos', via: 'get'
  match '/rules',     to: 'site#rules', via: 'get'
  match '/standings', to: 'site#standings', via: 'get'
  match '/participants', to: 'site#participants', via: 'get'
  match '/terms',      to: 'site#terms', via: 'get'
  match '/privacy',      to: 'site#privacy', via: 'get'
  match '/sitemap',      to: 'site#sitemap', via: 'get'
  
  match '/dashboard', to: 'dashboard#index',  via: 'get'

end

app/models/participant.rb
class Participant < ActiveRecord::Base
  mount_uploader :image, ImageUploader
end

app/controllers/participants_controller.rb
class ParticipantsController < ApplicationController
  before_action :set_participant, only: [:show, :edit, :update, :destroy]

  # GET /participants
  # GET /participants.json
  def index
    @participants = Participant.all
  end

  # GET /participants/1
  # GET /participants/1.json
  def show
  end

  # GET /participants/new
  def new
    @participant = Participant.new
  end

  # GET /participants/1/edit
  def edit
  end

  # POST /participants
  # POST /participants.json
  def create
    @participant = Participant.new(participant_params)

    respond_to do |format|
      if @participant.save
        format.html { redirect_to @participant, notice: 'Participant was successfully created.' }
        format.json { render action: 'show', status: :created, location: @participant }
      else
        format.html { render action: 'new' }
        format.json { render json: @participant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /participants/1
  # PATCH/PUT /participants/1.json
  def update
    respond_to do |format|
      if @participant.update(participant_params)
        format.html { redirect_to @participant, notice: 'Participant was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @participant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /participants/1
  # DELETE /participants/1.json
  def destroy
    @participant.destroy
    respond_to do |format|
      format.html { redirect_to participants_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_participant
      @participant = Participant.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def participant_params
      params.require(:participant).permit(:name, :content, :image, :enabled)
    end
end

app/views/participants/_form.html.haml
= form_for @participant do |f|
  - if @participant.errors.any?
    #error_explanation
      %h2= "#{pluralize(@participant.errors.count, "error")} prohibited this participant from being saved:"
      %ul
        - @participant.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :content
    = f.text_field :content
  .field
    = f.label :image
    = f.text_field :image
  .field
    = f.label :enabled
    = f.check_box :enabled
  .actions
    = f.submit 'Save'

app/views/participants/edit.html.haml
%h1 Editing participant

= render 'form'

= link_to 'Show', @participant
\|
= link_to 'Back', participants_path

app/views/participants/index.html.haml
%h1 Listing participants

%table
  %tr
    %th Name
    %th Content
    %th Image
    %th Enabled
    %th
    %th
    %th

  - @participants.each do |participant|
    %tr
      %td= participant.name
      %td= participant.content
      %td= participant.image
      %td= participant.enabled
      %td= link_to 'Show', participant
      %td= link_to 'Edit', edit_participant_path(participant)
      %td= link_to 'Destroy', participant, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Participant', new_participant_path

app/views/participants/new.html.haml
%h1 New participant

= render 'form'

= link_to 'Back', participants_path

app/views/participants/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @participant.name
%p
  %b Content:
  = @participant.content
%p
  %b Image:
  = @participant.image
%p
  %b Enabled:
  = @participant.enabled

= link_to 'Edit', edit_participant_path(@participant)
\|
= link_to 'Back', participants_path