config/routes.rb
Enegotiation::Application.routes.draw do

  resources :participants

  resources :top_standing_entries

  resources :top_standings

  devise_for :admins
  devise_for :users

  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  root to: 'site#home'

  resources :contact_forms

  match '/about',     to: 'site#about',   via: 'get'
  match '/team',      to: 'site#team',    via: 'get'
  match '/contact',   to: 'site#contact', via: 'get'
  match '/faq',       to: 'site#faq', via: 'get'
  match '/overview',  to: 'site#overview', via: 'get'
  match '/videos',    to: 'site#videos', via: 'get'
  match '/rules',     to: 'site#rules', via: 'get'
  match '/standings', to: 'site#standings', via: 'get'
  match '/participants', to: 'site#participants', via: 'get'
  match '/terms',      to: 'site#terms', via: 'get'
  match '/privacy',      to: 'site#privacy', via: 'get'
  match '/sitemap',      to: 'site#sitemap', via: 'get'
  
  match '/dashboard', to: 'dashboard#index',  via: 'get'

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/contact_form.rb
class ContactForm < MailForm::Base
  attribute :name,      :validate => true
  attribute :email,     :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i

  attribute :message
  attribute :nickname,  :captcha  => true

  # Declare the e-mail headers. It accepts anything the mail method
  # in ActionMailer accepts.
  def headers
    {
      :subject => "eNegotiation Exhibition Contact Form",
      :to => "derek.barber@smartsettle.com",
      :from => %("#{name}" <#{email}>)
    }
  end
end

app/models/course.rb
class Course < ActiveRecord::Base
  has_many :lessons
end

app/models/lesson.rb
class Lesson < ActiveRecord::Base
  belongs_to :course
end

app/models/participant.rb
class Participant < ActiveRecord::Base
  mount_uploader :image, ImageUploader
end

app/models/top_standing.rb
class TopStanding < ActiveRecord::Base
  has_many :top_standing_entries
end

app/models/top_standing_entry.rb
class TopStandingEntry < ActiveRecord::Base
  belongs_to :top_standing
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  before_save { email.downcase! }
  
  mount_uploader :avatar, AvatarUploader

  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  def after_sign_in_path_for(resource)
    dashboard_path
  end
end

app/controllers/contact_form_controller.rb
class ContactFormController < ApplicationController

  def new
    @contact_form = ContactForm.new
  end

  def create
    begin
      @contact_form = ContactForm.new(params[:contact_form])
      @contact_form.request = request
      if @contact_form.deliver
        flash.now[:notice] = 'Thank you for your message!'
      else
        render :new
      end
    rescue ScriptError
      flash[:error] = 'Sorry, this message appears to be spam and was not delivered.'
    end
  end
end

app/controllers/contact_forms_controller.rb
class ContactFormsController < ApplicationController

  def new
    @contact_form = ContactForm.new
  end

  def create
    begin
      @contact_form = ContactForm.new(params[:contact_form])
      @contact_form.request = request
      if @contact_form.deliver
        flash.now[:notice] = 'Thank you for your message!'
      else
        render :new
      end
    rescue ScriptError
      flash[:error] = 'Sorry, this message appears to be spam and was not delivered.'
    end
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  
end

app/controllers/participants_controller.rb
class ParticipantsController < ApplicationController
  before_action :set_participant, only: [:show, :edit, :update, :destroy]

  # GET /participants
  # GET /participants.json
  def index
    @participants = Participant.all
  end

  # GET /participants/1
  # GET /participants/1.json
  def show
  end

  # GET /participants/new
  def new
    @participant = Participant.new
  end

  # GET /participants/1/edit
  def edit
  end

  # POST /participants
  # POST /participants.json
  def create
    @participant = Participant.new(participant_params)

    respond_to do |format|
      if @participant.save
        format.html { redirect_to @participant, notice: 'Participant was successfully created.' }
        format.json { render action: 'show', status: :created, location: @participant }
      else
        format.html { render action: 'new' }
        format.json { render json: @participant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /participants/1
  # PATCH/PUT /participants/1.json
  def update
    respond_to do |format|
      if @participant.update(participant_params)
        format.html { redirect_to @participant, notice: 'Participant was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @participant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /participants/1
  # DELETE /participants/1.json
  def destroy
    @participant.destroy
    respond_to do |format|
      format.html { redirect_to participants_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_participant
      @participant = Participant.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def participant_params
      params.require(:participant).permit(:name, :content, :image, :enabled)
    end
end

app/controllers/site_controller.rb
class SiteController < ApplicationController
  layout "home", :only => :home

  def home
  end

  def about
  end

  def team
  end
  
  def faq
  end
  
  def overview
  end
  
  def videos
  end
  
  def rules
  end
end

app/controllers/top_standings_controller.rb
class TopStandingsController < ApplicationController

  def index
    @top_standings = TopStanding.all.order(:order => :desc)
  end

  def show
    @top_standing = TopStanding.find(params[:id])
    @top_standing_entries = @top_standing.top_standing_entries
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  
  # Returns the full title on a per-page basis
  def full_title(page_title)
    base_title = "The International eNegotiation Exhibition"
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end
end

app/helpers/contact_form_helper.rb
module ContactFormHelper
end

app/helpers/site_helper.rb
module SiteHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admins/shared/_links.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Sign in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/layouts/_footer.html.erb
<!-- FOOTER -->
<footer class="footer">
  <p class="pull-right"><a href="#">Back to top</a></p>
  <p>&copy; iCan Systems, Inc. &middot; 
    <%= link_to "Privacy", privacy_path %>
    &middot; 
    <%= link_to "Terms of Use", terms_path %>
  </p>
</footer>

app/views/layouts/_navigation.html.erb
<div class="navbar-inner">
  <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
    <span class="icon-bar"></span>
    <span class="icon-bar"></span>
    <span class="icon-bar"></span>
  </button>
  <%= link_to "eNegotiation Exhibition", root_path, id: "logo", class: "brand" %>
  <nav class="nav-collapse collapse">
    <ul class="nav pull-right">
      <li class="dropdown">
        <%= link_to 'About <b class="caret"></b>'.html_safe, about_path, :class => 'dropdown-toggle', :'data-toggle' => 'dropdown' %>
        <ul class="dropdown-menu">
          <li><%= link_to "About Us", about_path %></li>
          <li><%= link_to "Meet the Team", team_path %></li>
          <li><%= link_to "FAQ", faq_path %></li>
          <li><%= link_to "Contact", new_contact_form_path %></li>
        </ul>
      </li>
      <li class="dropdown">
        <%= link_to 'Participate <b class="caret"></b>'.html_safe, overview_path, :class => 'dropdown-toggle', :'data-toggle' => 'dropdown' %>
        <ul class="dropdown-menu">
          <li><%= link_to "Overview", overview_path %></li>
          <li><%= link_to "Watch Videos", videos_path %></li>
          <li><%= link_to "Rules", rules_path %></li>
        </ul>
      </li>
      <li class="dropdown">
        <%= link_to 'Standings <b class="caret"></b>'.html_safe, top_standings_path, :class => 'dropdown-toggle', :'data-toggle' => 'dropdown' %>
        <ul class="dropdown-menu">
          <li><%= link_to "Top Standings", top_standings_path %></li>
          <li><%= link_to "Participants", participants_path %></li>
        </ul>
      </li>

      <li class="dropdown">
        <% if user_signed_in? %>
          <%= link_to('Logout', destroy_user_session_path, :method => :delete)%>
        <% else %>
          <%= link_to "Sign in", new_user_session_path %>
        <% end %>
      </li>
    </ul>
  </nav><!--/.nav-collapse -->
</div><!-- /.navbar-inner -->

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= stylesheet_link_tag "site", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
</head>
<body>
  <header class="navbar navbar-fixed-top navbar-inverse">
    <%= render :partial => 'layouts/navigation' %>
  </header>
  <div class="container">
    <%= yield %>
    <%= render 'layouts/footer' %>
  </div>
</body>
</html>

app/views/layouts/home.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= stylesheet_link_tag "home-layout", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
</head>
<body>

  <header class="navbar-wrapper">
    <div class="container">
      <div class="navbar">
        <%= render :partial => 'layouts/navigation' %>
      </div>
    </div>
  </header>

<%= yield %>

<div class="container">
  <%= render 'layouts/footer' %>
</div>
</body>
</html>

app/views/shared/_flash_messages.html.erb
<% flash.each do |name, msg| %>
  <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
    <a class="close" data-dismiss="alert">×</a>
    <%= msg %>
  </div>
<% end %>